mAPI change for zmq3 (4.* version on repo; tested on Ubuntu 16)
ix-project/mutilate pull request #1
Opened 2019-03-12 18:29 UTC by ustiugov

2019-03-12 21:20 UTC, prekageo commented
Hi Dmitrii,

Can you let me know which problem you are trying to solve with this pull request? I am able to compile the source code as it is after installing the libzmq3-dev package on Ubuntu. It doesn't work for you?

2019-03-12 21:30 UTC, ustiugov commented
Hi George,
The build is broken on Ubuntu 14 and 16 due to libzmq package version problems. For example, here is the compilation error on Ubuntu 16 with libzmq3 installed (tested on icnals10 and one of the iccluster nodes):
```
g++ -o common.o -c -std=c++0x -D_GNU_SOURCE -O3 -Wall -g -I/usr/local/include -I/opt/local/include common.cc                                                                                               
common.cc: In function ‘void connect_agent()’:                                                                                                            
common.cc:349:38: error: no matching function for call to ‘zmq::socket_t::setsockopt(int, int)’                                                                                                            
     s->setsockopt(ZMQ_RCVTIMEO, 10000);                                                                                                                                                                   
                                      ^                                                                                                                                                                    
In file included from common.h:3:0,                                                                                                                                             
                 from common.cc:3:                                                                                                                                               
/usr/include/zmq.hpp:354:21: note: candidate: void zmq::socket_t::setsockopt(int, const void*, size_t)                                                                  
         inline void setsockopt (int option_, const void *optval_,                                                                                                     
                     ^~~~~~~~~~                                                                                                                                        
/usr/include/zmq.hpp:354:21: note:   candidate expects 3 arguments, 2 provided        
```
and after fixing it comes this one:
```
g++ -o mutilateudp.o -c -std=c++0x -D_GNU_SOURCE -O3 -Wall -g -I/usr/local/include -I/opt/local/include mutilateudp.cc
mutilateudp.cc: In function ‘void agent()’:
mutilateudp.cc:140:54: error: no matching function for call to ‘zmq::socket_t::bind(std::basic_string<char>)’
  socket.bind(string("tcp://*:") + args.agent_port_arg);
                                                      ^
In file included from mutilateudp.cc:4:0:
/usr/include/zmq.hpp:370:21: note: candidate: void zmq::socket_t::bind(const char*)
         inline void bind (const char *addr_)
                     ^~~~
/usr/include/zmq.hpp:370:21: note:   no known conversion for argument 1 from ‘std::basic_string<char>’ to ‘const char*’
```

Marios reproduced with a *newly* cloned repo the first error on icnals10. My guess is that the system got upgraded so the package `libzmq-dev` got a new version on that platform.  I had to fix a couple of incompatible API calls so that mutilate works with `libzmq3` package on Ubuntu 14.

2019-03-12 21:49 UTC, prekageo commented
I see what might be the problem. Check if you have installed the libzmq-dev package:

```dpkg --get-selections | grep libzmq```

If yes, I suggest that you remove all libzmq packages and install only libzmq3-dev.

I agree that the situation with the zmq dependency is confusing. I have been confused myself many times!

2019-03-13 11:33 UTC, ustiugov commented
George,
I have the following output on my Ubuntu 14 node:
```ustiugov@iccluster041:~/faas_study/mutilate$ dpkg --get-selections | grep libzmq                                          
libzmq1:amd64                                   deinstall                                                                 
libzmq3:amd64                                   install                                                       
libzmq3-dev:amd64                               install  
```
The compilation error is still there even though other libs are removed. Are you sure you tried a clean build?

2019-03-13 14:34 UTC, prekageo commented
You are right. Your patch is necessary on Ubuntu Trusty. I have some long standing pending patches that I'd like to push first. I'll ask you to update your pull request once I do the push. Thanks!

2019-03-13 15:23 UTC, ustiugov commented
Please go ahead, no rush. Thanks!

On 13 Mar 2019, at 14:35, George Prekas <notifications@github.com<mailto:notifications@github.com>> wrote:


You are right. Your patch is necessary on Ubuntu Trusty. I have some long standing pending patches that I'd like to push first. I'll ask you to update your pull request once I do the push. Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/ix-project/mutilate/pull/1#issuecomment-472447563>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AO7TuoMB_XsCds7lC6OMtaFKuPPQt5SPks5vWQyrgaJpZM4brmB9>.

2019-03-14 04:43 UTC, prekageo requested changes
Please rebase on top of the new master. Squash your commits to a single one with a message like "fix zmq for older Ubuntu".

Thanks for your effort!

2019-03-14 04:43 UTC, prekageo commented on common.cc
> +    int64_t timeout = 10000;
```suggestion
    int timeout = 10000;
```

The parameter must be int. It is checked by zmq.

2019-03-14 11:20 UTC, ustiugov commented
ok, ready for the merge. Thanks!

2019-03-15 01:36 UTC, merged